In [26]:
import numpy as np

#function to get list of possible outcomes for rolls with "num_die" die
def make_die_list(num_die):
    to_ret = list()
    if(num_die == 1):
        return [[1],[2],[3],[4],[5],[6]]
    for i in range(1,7):
        for l in make_die_list(num_die - 1):
            l.append(i)
            to_ret.append(l)
    return to_ret


def get_transition_probs(num_of_die_rolled):
    to_ret = np.zeros([1,5])
    
    if(num_of_die_rolled == 0):
        #return row where 100% chance to remain in same Yahtzee state
        to_ret[(0,0)] = 1 
        return to_ret
    
    #Since die not rolled are the same and their number does not matter, we initialize them as ones
    saved_die = [1]*(5-num_of_die_rolled)
    
    possible_outcomes = make_die_list(num_of_die_rolled)
    for o in possible_outcomes:
        
        if num_of_die_rolled != 5:
            o.extend(saved_die)
            #without this if statement, if we roll five dice the outcome is [#,#,#,#,#,[]] which doesnt make sense
            
        counts = {item:o.count(item) for item in o}
        max_num = max(list(counts.values()))
        to_ret[(0,max_num-1)] += 1
        
    #reshape results so transition probability rows will combine into transition probability matricx well
    to_ret = np.fliplr(to_ret)
    
    #convert outcomes to probability by dividing by number of possible outcomes
    return to_ret/ 6**num_of_die_rolled

In [23]:
for i in range(5,0,-1):
    if i == 5:
        running_trans = get_transition_probs(5-i)
    else:
        running_trans = np.concatenate((running_trans,get_transition_probs(5-i))) #,axis=1
list((running_trans))

[array([1., 0., 0., 0., 0.]),
 array([0.16666667, 0.83333333, 0.        , 0.        , 0.        ]),
 array([0.02777778, 0.27777778, 0.69444444, 0.        , 0.        ]),
 array([0.00462963, 0.06944444, 0.37037037, 0.55555556, 0.        ]),
 array([0.0007716 , 0.01929012, 0.19290123, 0.69444444, 0.09259259])]

In [24]:
#multiply transition probability matrix by itself three times
np.dot(running_trans,running_trans,running_trans)

array([[1.        , 0.        , 0.        , 0.        , 0.        ],
       [0.30555556, 0.69444444, 0.        , 0.        , 0.        ],
       [0.0933642 , 0.42438272, 0.48225309, 0.        , 0.        ],
       [0.02906379, 0.19933128, 0.46296296, 0.30864198, 0.        ],
       [0.01263146, 0.11967021, 0.40902206, 0.45010288, 0.00857339]])

In [25]:
#final result
running_trans[(4,0)]

0.012631458619112938